version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_wb
    ports:
      - "17200:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nats:
    container_name: nats-streaming
    image: nats-streaming
    command: ["-p", "4222", "-m", "8222", "--store", "file", "--dir", "/data"]
    restart: always
    ports:
      - "4222:4222" # для обмена сообщениями
      - "8222:8222" #  для мониторинга и администрирования
    volumes:
      - ./data/nats:/data
      -
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
