version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_wb
    ports:
      - "17200:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
